[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyCallisto"
version = "1.0.0"
description = "Python tools for analyzing Callisto solar radio spectrometer data"
readme = "README.md"
authors = [
    {name = "Ravi Pawase", email = "your_email@example.com"}
]
license = {file = "LICENSE"}
keywords = ["astronomy", "solar radio", "spectrometer", "data analysis"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "astropy",
    "pandas"
]

[project.urls]
Homepage = "https://github.com/ravipawase/pyCallisto"
Documentation = "https://github.com/ravipawase/pyCallisto/wiki"
Repository = "https://github.com/ravipawase/pyCallisto"
Issues = "https://github.com/ravipawase/pyCallisto/issues"
